def display_help():
    print("\n==================== HELP ====================")
    print(" ")
    print("1. **View Stocks** - View details of all available stocks in the database.")
    print("2. **Top Market Recommendations** - Get top recommended stocks based on various financial metrics.")
    print("3. **Industry Classifier** - View and analyze stocks by industry. Further options allow you to:")
    print("   - Display stocks by industry.")
    print("   - Get top stock recommendations by industry.")
    print("   - Find industry stocks with the lowest debt-to-equity ratio.")
    print("   - Find industry stocks with the best YoY growth.")
    print("   - Find industry stocks with the highest dividend yield.")
    print("4. **Pro Stock Sorter** - Sort stocks based on specific financial metrics, including:")
    print("   - Lowest debt stocks.")
    print("   - Best performing growth stocks.")
    print("   - High dividend yield stocks.")
    print("5. **Add and Update Company Data** - Add a new company or update data for an existing company.")
    print("6. **Search Company By Name** - Search for a specific company by name to view its detailed stock information.")
    print("7. **Help** - Display information about each menu option to guide users.")
    print("8. **Exit** - Close the application.")
    print("\n**Note**: To use Industry Classifier and Pro Stock Sorter effectively,")
    print(            "ensure the industry names and company data are correctly entered in the database.")
    print("\n**Disclaimer**: Investing by following recommendations or insights from this system is at your own risk.")
    print(                  "Please conduct your own research and consult with a financial advisor if needed.")
    print("=============================================\n")
